package com.example.provide.entity;

import com.alibaba.fastjson.JSONObject;
import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.util.Arrays;
import java.util.List;

@Data
@Builder
public class User implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.id
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.userName
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.sex
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_user
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.id
     *
     * @return the value of tb_user.id
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.id
     *
     * @param id the value for tb_user.id
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.userName
     *
     * @return the value of tb_user.userName
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.userName
     *
     * @param username the value for tb_user.userName
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.sex
     *
     * @return the value of tb_user.sex
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.sex
     *
     * @param sex the value for tb_user.sex
     *
     * @mbg.generated Wed Mar 18 15:00:06 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    public static void main(String[] args) {
        List<Config> configBuilders = Arrays.asList(Config.builder().dataId("1").refresh(true).group("DEFAULT_GROUP").build(), Config.builder().dataId("1").group("DEFAULT_GROUP").refresh(true).build());
        String s = JSONObject.toJSONString(configBuilders);
        System.out.println(s);
    }
    @Data
    @Builder
    static class Config{
        private String dataId;
        private String group = "DEFAULT_GROUP";
        private boolean refresh = false;

    }
}